"""add_certificate_and_rank_boss_tables

Revision ID: 53902275681a
Revises: 53ec0dd9fb0d
Create Date: 2026-06-07 08:07:40.672082
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53902275681a'
down_revision = '53ec0dd9fb0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('certificate_type', sa.String(length=30), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('listening_score', sa.Float(), nullable=True),
    sa.Column('reading_score', sa.Float(), nullable=True),
    sa.Column('writing_score', sa.Float(), nullable=True),
    sa.Column('speaking_score', sa.Float(), nullable=True),
    sa.Column('input_method', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificate_records_id'), 'certificate_records', ['id'], unique=False)
    
    op.create_table('rank_exam_pools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('from_rank', sa.String(length=5), nullable=False),
    sa.Column('to_rank', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pass_percent', sa.Integer(), nullable=False),
    sa.Column('default_time_limit_minutes', sa.Integer(), nullable=False),
    sa.Column('max_attempts_per_day', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rank_exam_pools_id'), 'rank_exam_pools', ['id'], unique=False)
    op.create_index('ix_rank_exam_pools_skill_rank', 'rank_exam_pools', ['skill_id', 'from_rank', 'to_rank'], unique=False)
    
    op.create_table('rank_exam_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('version_code', sa.String(length=80), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=30), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['rank_exam_pools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rank_exam_versions_id'), 'rank_exam_versions', ['id'], unique=False)
    op.create_index('ix_rank_exam_versions_pool_id', 'rank_exam_versions', ['pool_id'], unique=False)
    
    op.create_table('rank_exam_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('from_rank', sa.String(length=5), nullable=False),
    sa.Column('to_rank', sa.String(length=5), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('exam_version_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('score_points', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('score_percent', sa.Float(), nullable=True),
    sa.Column('pass_percent', sa.Integer(), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['exam_version_id'], ['rank_exam_versions.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['rank_exam_pools.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rank_exam_attempts_campaign_skill', 'rank_exam_attempts', ['campaign_id', 'skill_id'], unique=False)
    op.create_index(op.f('ix_rank_exam_attempts_id'), 'rank_exam_attempts', ['id'], unique=False)
    op.create_index('ix_rank_exam_attempts_started_at', 'rank_exam_attempts', ['started_at'], unique=False)
    op.create_index('ix_rank_exam_attempts_status', 'rank_exam_attempts', ['status'], unique=False)
    
    op.create_table('rank_exam_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_version_id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('options_json', sa.JSON(), nullable=True),
    sa.Column('correct_answer_json', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_version_id'], ['rank_exam_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rank_exam_questions_exam_version_id', 'rank_exam_questions', ['exam_version_id'], unique=False)
    op.create_index(op.f('ix_rank_exam_questions_id'), 'rank_exam_questions', ['id'], unique=False)
    
    op.create_table('rank_exam_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_json', sa.JSON(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['rank_exam_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['rank_exam_questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_rank_exam_answer_attempt_question')
    )
    op.create_index(op.f('ix_rank_exam_answers_id'), 'rank_exam_answers', ['id'], unique=False)
    
    op.add_column('campaign_skill_states', sa.Column('pending_rank', sa.String(length=5), nullable=True))
    op.add_column('campaign_skill_states', sa.Column('promotion_status', sa.String(length=30), nullable=False, server_default='none'))
    op.add_column('campaign_skill_states', sa.Column('promotion_unlocked_at', sa.DateTime(), nullable=True))
    op.add_column('campaign_skill_states', sa.Column('last_rank_exam_attempt_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_campaign_skill_states_last_rank_exam_attempt_id', 'campaign_skill_states', 'rank_exam_attempts', ['last_rank_exam_attempt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_campaign_skill_states_last_rank_exam_attempt_id', 'campaign_skill_states', type_='foreignkey')
    op.drop_column('campaign_skill_states', 'last_rank_exam_attempt_id')
    op.drop_column('campaign_skill_states', 'promotion_unlocked_at')
    op.drop_column('campaign_skill_states', 'promotion_status')
    op.drop_column('campaign_skill_states', 'pending_rank')
    
    op.drop_index(op.f('ix_rank_exam_answers_id'), table_name='rank_exam_answers')
    op.drop_table('rank_exam_answers')
    op.drop_index(op.f('ix_rank_exam_questions_id'), table_name='rank_exam_questions')
    op.drop_index('ix_rank_exam_questions_exam_version_id', table_name='rank_exam_questions')
    op.drop_table('rank_exam_questions')
    op.drop_index('ix_rank_exam_attempts_status', table_name='rank_exam_attempts')
    op.drop_index('ix_rank_exam_attempts_started_at', table_name='rank_exam_attempts')
    op.drop_index(op.f('ix_rank_exam_attempts_id'), table_name='rank_exam_attempts')
    op.drop_index('ix_rank_exam_attempts_campaign_skill', table_name='rank_exam_attempts')
    op.drop_table('rank_exam_attempts')
    op.drop_index('ix_rank_exam_versions_pool_id', table_name='rank_exam_versions')
    op.drop_index(op.f('ix_rank_exam_versions_id'), table_name='rank_exam_versions')
    op.drop_table('rank_exam_versions')
    op.drop_index('ix_rank_exam_pools_skill_rank', table_name='rank_exam_pools')
    op.drop_index(op.f('ix_rank_exam_pools_id'), table_name='rank_exam_pools')
    op.drop_table('rank_exam_pools')
    op.drop_index(op.f('ix_certificate_records_id'), table_name='certificate_records')
    op.drop_table('certificate_records')
    # ### end Alembic commands ###
