"""add_campaign_template_and_quotas

Revision ID: 53ec0dd9fb0d
Revises: b14757712bca
Create Date: 2026-06-07 08:01:29.826735
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ec0dd9fb0d'
down_revision = 'b14757712bca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('certificate_type', sa.String(length=30), nullable=False),
    sa.Column('target_band', sa.String(length=20), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('total_weeks', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_campaign_templates_code')
    )
    op.create_index(op.f('ix_campaign_templates_code'), 'campaign_templates', ['code'], unique=False)
    op.create_index(op.f('ix_campaign_templates_id'), 'campaign_templates', ['id'], unique=False)
    
    op.create_table('campaign_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('target_certificate', sa.String(length=30), nullable=False),
    sa.Column('target_band', sa.String(length=20), nullable=False),
    sa.Column('current_english_level', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('target_test_date', sa.Date(), nullable=True),
    sa.Column('study_duration_months', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', name='uq_campaign_settings_campaign_id')
    )
    op.create_index(op.f('ix_campaign_settings_id'), 'campaign_settings', ['id'], unique=False)
    
    op.create_table('campaign_skill_quest_quotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('daily_quota', sa.Integer(), nullable=False),
    sa.Column('weekly_quota', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('preferred_activity_types', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'skill_id', name='uq_campaign_skill_quest_quota')
    )
    op.create_index(op.f('ix_campaign_skill_quest_quotas_id'), 'campaign_skill_quest_quotas', ['id'], unique=False)
    
    op.create_table('campaign_template_skill_quotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_template_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('daily_quota', sa.Integer(), nullable=False),
    sa.Column('weekly_quota', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('preferred_activity_types', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_template_id'], ['campaign_templates.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_template_id', 'skill_id', name='uq_template_skill_quota')
    )
    op.create_index(op.f('ix_campaign_template_skill_quotas_id'), 'campaign_template_skill_quotas', ['id'], unique=False)
    
    op.create_table('player_learning_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('preferred_learning_style', sa.String(length=50), nullable=False),
    sa.Column('dictionary_mode', sa.String(length=50), nullable=False),
    sa.Column('pronunciation_focus', sa.Boolean(), nullable=False),
    sa.Column('collocation_focus', sa.Boolean(), nullable=False),
    sa.Column('native_language', sa.String(length=50), nullable=False),
    sa.Column('interface_learning_language', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', name='uq_player_learning_profiles_player_id')
    )
    op.create_index(op.f('ix_player_learning_profiles_id'), 'player_learning_profiles', ['id'], unique=False)
    
    op.create_table('vocabulary_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('daily_new_words_target', sa.Integer(), nullable=False),
    sa.Column('daily_flashcard_target', sa.Integer(), nullable=False),
    sa.Column('daily_collocation_target', sa.Integer(), nullable=False),
    sa.Column('daily_context_hunt_target', sa.Integer(), nullable=False),
    sa.Column('daily_error_review_target', sa.Integer(), nullable=False),
    sa.Column('vocab_review_mode', sa.String(length=50), nullable=False),
    sa.Column('vocab_grouping_mode', sa.String(length=50), nullable=False),
    sa.Column('dictionary_mode', sa.String(length=50), nullable=False),
    sa.Column('example_sentence_required', sa.Boolean(), nullable=False),
    sa.Column('pronunciation_required', sa.Boolean(), nullable=False),
    sa.Column('word_family_required', sa.Boolean(), nullable=False),
    sa.Column('synonym_antonym_required', sa.Boolean(), nullable=False),
    sa.Column('collocation_required', sa.Boolean(), nullable=False),
    sa.Column('spaced_repetition_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', name='uq_vocabulary_settings_campaign_id')
    )
    op.create_index(op.f('ix_vocabulary_settings_id'), 'vocabulary_settings', ['id'], unique=False)
    
    op.add_column('campaigns', sa.Column('campaign_template_id', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('setup_completed', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('campaigns', sa.Column('setup_completed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_campaigns_campaign_template_id'), 'campaigns', ['campaign_template_id'], unique=False)
    op.create_foreign_key('fk_campaigns_campaign_template_id', 'campaigns', 'campaign_templates', ['campaign_template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_campaigns_campaign_template_id', 'campaigns', type_='foreignkey')
    op.drop_index(op.f('ix_campaigns_campaign_template_id'), table_name='campaigns')
    op.drop_column('campaigns', 'setup_completed_at')
    op.drop_column('campaigns', 'setup_completed')
    op.drop_column('campaigns', 'campaign_template_id')
    
    op.drop_index(op.f('ix_vocabulary_settings_id'), table_name='vocabulary_settings')
    op.drop_table('vocabulary_settings')
    
    op.drop_index(op.f('ix_player_learning_profiles_id'), table_name='player_learning_profiles')
    op.drop_table('player_learning_profiles')
    
    op.drop_index(op.f('ix_campaign_template_skill_quotas_id'), table_name='campaign_template_skill_quotas')
    op.drop_table('campaign_template_skill_quotas')
    
    op.drop_index(op.f('ix_campaign_skill_quest_quotas_id'), table_name='campaign_skill_quest_quotas')
    op.drop_table('campaign_skill_quest_quotas')
    
    op.drop_index(op.f('ix_campaign_settings_id'), table_name='campaign_settings')
    op.drop_table('campaign_settings')
    
    op.drop_index(op.f('ix_campaign_templates_id'), table_name='campaign_templates')
    op.drop_index(op.f('ix_campaign_templates_code'), table_name='campaign_templates')
    op.drop_table('campaign_templates')
    # ### end Alembic commands ###
