"""add_collocation_master_data

Revision ID: 950b4a9af4c2
Revises: d4fcb0a83bb2
Create Date: 2026-06-08 09:13:45.391534
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '950b4a9af4c2'
down_revision = 'd4fcb0a83bb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collocation_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_book', sa.String(length=255), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collocation_collections_code'), 'collocation_collections', ['code'], unique=True)
    op.create_index(op.f('ix_collocation_collections_id'), 'collocation_collections', ['id'], unique=False)
    op.create_table('campaign_collocation_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collocation_collections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'collection_id', name='uq_campaign_colcol_link')
    )
    op.create_index(op.f('ix_campaign_collocation_links_id'), 'campaign_collocation_links', ['id'], unique=False)
    op.create_table('collocation_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('section_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collocation_collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_collocation_sections_collection_order', 'collocation_sections', ['collection_id', 'section_order'], unique=False)
    op.create_index(op.f('ix_collocation_sections_id'), 'collocation_sections', ['id'], unique=False)
    op.create_table('collocation_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('topic_number', sa.Integer(), nullable=True),
    sa.Column('topic_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['collocation_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collocation_topics_id'), 'collocation_topics', ['id'], unique=False)
    op.create_index('ix_collocation_topics_section_order', 'collocation_topics', ['section_id', 'topic_order'], unique=False)
    op.create_table('collocation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('collocation', sa.String(length=255), nullable=False),
    sa.Column('pronunciation_us', sa.String(length=255), nullable=True),
    sa.Column('meaning_vi', sa.Text(), nullable=True),
    sa.Column('example_en', sa.Text(), nullable=True),
    sa.Column('example_vi', sa.Text(), nullable=True),
    sa.Column('collocation_type', sa.String(length=100), nullable=True),
    sa.Column('item_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['collocation_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collocation_items_id'), 'collocation_items', ['id'], unique=False)
    op.create_index('ix_collocation_items_topic_order', 'collocation_items', ['topic_id', 'item_order'], unique=False)
    op.create_table('player_collocation_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('collocation_item_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('practice_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('last_practiced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['collocation_item_id'], ['collocation_items.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'campaign_id', 'collocation_item_id', name='uq_player_camp_col_item')
    )
    op.create_index('ix_pcp_campaign_status', 'player_collocation_progress', ['campaign_id', 'status'], unique=False)
    op.create_index('ix_pcp_player_campaign', 'player_collocation_progress', ['player_id', 'campaign_id'], unique=False)
    op.create_index(op.f('ix_player_collocation_progress_id'), 'player_collocation_progress', ['id'], unique=False)
    op.drop_index('idx_flashcards_player_id', table_name='flashcards')
    op.drop_table('vocabulary_collocations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary_collocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_item_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('collocation', sa.String(length=255), nullable=False),
    sa.Column('collocation_type', sa.String(length=100), nullable=True),
    sa.Column('example_sentence', sa.Text(), nullable=True),
    sa.Column('example_meaning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['vocabulary_item_id'], ['vocabulary_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vocabulary_collocations_id', 'vocabulary_collocations', ['id'], unique=False)
    op.create_index('ix_vocabulary_collocations_player_id', 'vocabulary_collocations', ['player_id'], unique=False)
    op.create_index('ix_vocabulary_collocations_vocabulary_item_id', 'vocabulary_collocations', ['vocabulary_item_id'], unique=False)

    op.create_index('idx_flashcards_player_id', 'flashcards', ['player_id'], unique=False)
    op.drop_index(op.f('ix_player_collocation_progress_id'), table_name='player_collocation_progress')
    op.drop_index('ix_pcp_player_campaign', table_name='player_collocation_progress')
    op.drop_index('ix_pcp_campaign_status', table_name='player_collocation_progress')
    op.drop_table('player_collocation_progress')
    op.drop_index('ix_collocation_items_topic_order', table_name='collocation_items')
    op.drop_index(op.f('ix_collocation_items_id'), table_name='collocation_items')
    op.drop_table('collocation_items')
    op.drop_index('ix_collocation_topics_section_order', table_name='collocation_topics')
    op.drop_index(op.f('ix_collocation_topics_id'), table_name='collocation_topics')
    op.drop_table('collocation_topics')
    op.drop_index(op.f('ix_collocation_sections_id'), table_name='collocation_sections')
    op.drop_index('ix_collocation_sections_collection_order', table_name='collocation_sections')
    op.drop_table('collocation_sections')
    op.drop_index(op.f('ix_campaign_collocation_links_id'), table_name='campaign_collocation_links')
    op.drop_table('campaign_collocation_links')
    op.drop_index(op.f('ix_collocation_collections_id'), table_name='collocation_collections')
    op.drop_index(op.f('ix_collocation_collections_code'), table_name='collocation_collections')
    op.drop_table('collocation_collections')
    # ### end Alembic commands ###
