"""add_account_auth_tables

Revision ID: b14757712bca
Revises: 089adadeddde
Create Date: 2026-06-07 07:52:56.541164
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = 'b14757712bca'
down_revision = '089adadeddde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_normalized', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('onboarding_completed_at', sa.DateTime(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_normalized', name='uq_accounts_email_normalized')
    )
    op.create_index(op.f('ix_accounts_email_normalized'), 'accounts', ['email_normalized'], unique=False)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_table('account_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('theme', sa.String(length=30), nullable=False),
    sa.Column('accent_color', sa.String(length=30), nullable=True),
    sa.Column('notification_enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_reminder_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', name='uq_account_preferences_account_id')
    )
    op.create_index(op.f('ix_account_preferences_id'), 'account_preferences', ['id'], unique=False)
    op.create_table('account_security_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('email_attempted', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_security_events_account_id'), 'account_security_events', ['account_id'], unique=False)
    op.create_index('ix_account_security_events_created_at', 'account_security_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_account_security_events_event_type'), 'account_security_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_account_security_events_id'), 'account_security_events', ['id'], unique=False)
    op.create_table('account_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoke_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash', name='uq_account_sessions_refresh_token_hash')
    )
    op.create_index(op.f('ix_account_sessions_account_id'), 'account_sessions', ['account_id'], unique=False)
    op.create_index('ix_account_sessions_expires_at', 'account_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_account_sessions_id'), 'account_sessions', ['id'], unique=False)
    op.create_table('account_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_account_tokens_token_hash')
    )
    op.create_index('ix_account_tokens_account_purpose', 'account_tokens', ['account_id', 'purpose'], unique=False)
    op.create_index(op.f('ix_account_tokens_id'), 'account_tokens', ['id'], unique=False)
    
    op.add_column('players', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_players_account_id'), 'players', ['account_id'], unique=True)
    op.create_foreign_key(None, 'players', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_index(op.f('ix_players_account_id'), table_name='players')
    op.drop_column('players', 'account_id')
    
    op.drop_index(op.f('ix_account_tokens_id'), table_name='account_tokens')
    op.drop_index('ix_account_tokens_account_purpose', table_name='account_tokens')
    op.drop_table('account_tokens')
    op.drop_index(op.f('ix_account_sessions_id'), table_name='account_sessions')
    op.drop_index('ix_account_sessions_expires_at', table_name='account_sessions')
    op.drop_index(op.f('ix_account_sessions_account_id'), table_name='account_sessions')
    op.drop_table('account_sessions')
    op.drop_index(op.f('ix_account_security_events_id'), table_name='account_security_events')
    op.drop_index(op.f('ix_account_security_events_event_type'), table_name='account_security_events')
    op.drop_index('ix_account_security_events_created_at', table_name='account_security_events')
    op.drop_index(op.f('ix_account_security_events_account_id'), table_name='account_security_events')
    op.drop_table('account_security_events')
    op.drop_index(op.f('ix_account_preferences_id'), table_name='account_preferences')
    op.drop_table('account_preferences')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_email_normalized'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
